name = "TensorKit"
uuid = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
authors = ["Jutho Haegeman"]
version = "0.10.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[compat]
Strided = "1.0.1"
TupleTools = "1.1"
HalfIntegers = "1"
WignerSymbols = "1,2"
TensorOperations = "3.2.3"
LRUCache = "1.0.2"
julia = "1.6"
